version: '3'

services:
  redis-dev:
    container_name: redis-dev
    image: redis:3.2.10
    networks:
      devnet:
        aliases:
          - redis
    ports:
      - "6379:6379"
  es-dev:
    container_name: es-dev
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      devnet:
        aliases:
          - elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=myCluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
          soft: -1
          hard: -1
  es2-dev:
    container_name: es2-dev
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - cluster.name=myCluster
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
          soft: -1
          hard: -1
  kibana-dev:
    container_name: kibana-dev
    image: docker.elastic.co/kibana/kibana:6.4.0
    networks:
        devnet:
          aliases:
            - kibana
    ports:
      - "5601:5601"

networks:
  devnet: